// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClseBpL5117W0qVhccAZ0drd8G6jkeEMM',
    appId: '1:326547043793:web:220755560a09f80d8f1cf0',
    messagingSenderId: '326547043793',
    projectId: 'askcam-ef660',
    authDomain: 'askcam-ef660.firebaseapp.com',
    storageBucket: 'askcam-ef660.firebasestorage.app',
    measurementId: 'G-YLQPHTVSHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQww8WtkFxQD_MRn2xUgJPDr-2oET7xgU',
    appId: '1:326547043793:android:a9409f44b9c9b7278f1cf0',
    messagingSenderId: '326547043793',
    projectId: 'askcam-ef660',
    storageBucket: 'askcam-ef660.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpir6B-51JCEc_UF50jsj-TgOzol0dCkQ',
    appId: '1:326547043793:ios:38f03f6570b753e58f1cf0',
    messagingSenderId: '326547043793',
    projectId: 'askcam-ef660',
    storageBucket: 'askcam-ef660.firebasestorage.app',
    iosBundleId: 'askcam.example.askcam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpir6B-51JCEc_UF50jsj-TgOzol0dCkQ',
    appId: '1:326547043793:ios:38f03f6570b753e58f1cf0',
    messagingSenderId: '326547043793',
    projectId: 'askcam-ef660',
    storageBucket: 'askcam-ef660.firebasestorage.app',
    iosBundleId: 'askcam.example.askcam',
  );
}
